rescript-react-native/rescript-react-navigation

src/AppContainer.bs.js
src/AppContainer.re
src/AppContainerFunctor.bs.js
src/AppContainerFunctor.re

* The functor-based version should be easier to use for beginners as it gives you a normal ReasonReact component (module). But it is not zero-cost.
* The non-functor-based version is zero-cost, but you need to do `React.createElement(...)` yourself. It allows advanced use cases such as (re)creating your AppContainer based e.g. on permission changes.

AppContainer binding: provide both a functor-based and a functor-less version

---

package.json
src/DrawerNavigator.re
src/StackNavigator.re
src/TabNavigator.re
yarn.lock

I assume this will also break the example. After this + all the repo/package renaming is through, we should get the example to work again.

Support react-navigation 4.0.x (breaking change).

---

example/src/components/Search.re
src/Navigation.re

Add the addListener binding.

---

src/StackNavigator.re

Hello,
I just add a new param, it might be cool in the future to have a `NavigationOptions.t` for each navigator (in order to avoid bad props).

Add defaultNavigationOptions params to StackNavigator config

---

src/Navigation.re

My motivation:
https://reactnavigation.org/docs/en/header-buttons.html#header-interaction-with-its-screen-component

feature: Navigation.setParams

---

src/AppContainer.re

Don't know why I had `setNavigatorRef` here when I created the bindings - must have been some kind of copy/paste error.

Fix AppContainer (setNavigatorRef -> ref)

---

src/BottomTabs.bs.js
src/Drawer.bs.js
src/Drawer.re
src/Example.bs.js
src/MaterialBottomTabs.bs.js
src/MaterialTopTabs.bs.js
src/Stack.bs.js

Hi,
It looks like the API name for some props has changed since the binding creation
Closes #<number-of-the-issue>

fix: Fix drawerContent & drawerContentOptions props for Drawer navigator

---

src/Example.re

in #28 we added a comment for noobs that says we should uncomment this line. It is however not commented out within the repo. This comments it out

Comment out "open ReactNavigation;" in example

---

src/BottomTabs.re
src/MaterialTopTabs.re

`tabBarComponent` doesn't exist in the react-navigation props, it's `tabBar` only.
For now, it compile to this and it doesn't work:
```js
return React.createElement($$Navigator.make, {
children: children,
tabBarComponent: CustomTopTabBar$TopTabBar,
tabBarOptions: tabBarOptions
});
```

update tabBarComponent to tabBar

---

src/Example.bs.js
src/Example.re
src/Stack.bs.js
src/Stack.re

Feature for render callback of stack screen

---

src/BottomTabs.bs.js
src/BottomTabs.re
src/MaterialBottomTabs.bs.js
src/MaterialBottomTabs.re
src/MaterialTopTabs.bs.js
src/MaterialTopTabs.re
src/Stack.re

ScreenWithCallback for BottomTabs, MaterialBottomTabs and MaterialTopTabs navigators, to match the Stack navigator.

ScreenWithCallback for tabs navigators

---

src/BottomTabs.re
src/Drawer.re
src/MaterialBottomTabs.re
src/MaterialTopTabs.re
src/Native.re
src/Stack.re

- Add ref prop to NavigationContainer (important for universal link scenario)
- Add key prop to components

Add react ref and key props to components

---

package.json

Closes #38
Not sure if this is a correct solution but it seems npm is using `files` as `.npmignore`

fix: include missing Interop.js in package files

---

src/Native.re

Hello.
Looks like  `NavigationContainer` ref has `NavigationContainerRef ` type: [packages/native/src/NavigationContainer.tsx#L47](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/NavigationContainer.tsx#L47)
These changes will make it possible to use [navigation without `navigation` prop](https://reactnavigation.org/docs/navigating-without-navigation-prop).

Fix NavigationContainer ref type

---

src/Core.bs.js
src/Core.res

The underlying `navigateBy` function didn't accept `navigation`, so it wasn't working. I wired up the `navigation` param in `navigateByKey` and `navigateByName`.

Fix `navigateBy*` functions

---

package.json
src/BottomTabs.bs.js
src/BottomTabs.res
src/Core.bs.js
src/Core.res
src/Drawer.bs.js
src/Drawer.res
src/Example.bs.js
src/Example.res
src/MaterialBottomTabs.bs.js
src/MaterialBottomTabs.res
src/MaterialTopTabs.bs.js
src/MaterialTopTabs.res
src/NativeStack.bs.js
src/NativeStack.res
src/Stack.bs.js
src/Stack.res

I followed https://reactnavigation.org/docs/upgrading-from-5.x, but there might be things that are not covered. However, this is enough for us to use React Navigation 6 in a not-so-small React Native (ReScript + TypeScript) app.
I upgraded package version from 5.2.0 to 6.0.0.
Closes #43

Upgrade to React Navigation 6.x

---

src/Drawer.bs.js
src/Drawer.res

Hi!
I have changed few things:
- add missing options
- enable creating screen with children (`ScreenWithCallback`)
- small improvements in existing options
Type reference:
- [DrawerNavigationOptions](https://github.com/react-navigation/react-navigation/blob/b91c9b05ff96727f5fa6ef0bec51b5d7eac06600/packages/drawer/src/types.tsx#L52)
- [HeaderOptions](https://github.com/react-navigation/react-navigation/blob/82a16690973a7935939a25a66d5786955b6c8ba7/packages/elements/src/types.tsx#L11)
NOTE: The only option I didn't add is `header`, but I left it commented out. I wasn't sure if I could do it properly even though I had a reference in `Stack`.
NOTE: These changes introduce a **breaking change** since I changed the type of `drawerLabel` to be able to accept `string` along the `render fn`.

Improve `Drawer`

---

src/MaterialTopTabs.res
src/Stack.res

Hi!
I improved `Stack` binding by adding:
- `headerBackTestID` option
- `getId` screen prop
and improved `MaterialTopTabs` by adding `swipeEnabled` screen option since setting it through props is deprecated.

Improve stack and material top tabs

---

bsconfig.json
package-lock.json
package.json
src/BottomTabs.bs.js
src/BottomTabs.res
src/Core.bs.js
src/Core.res
src/Drawer.bs.js
src/Drawer.res
src/Elements.bs.js
src/Elements.res
src/Example.bs.js
src/Example.res
src/Interop.js
src/MaterialBottomTabs.bs.js
src/MaterialBottomTabs.res
src/MaterialTopTabs.bs.js
src/MaterialTopTabs.res
src/Native.bs.js
src/Native.res
src/NativeStack.bs.js
src/NativeStack.res
src/NavigationState.res
src/Stack.bs.js
src/Stack.res

This is more or less a full rewrite of the existing bindings that I implemented for our company's projects in the last months.
It is meant for the latest ReScript (10.1.2) + @rescript/react 0.11.0 in JSX4 mode.
It
- supports JSX4 (exclusively, although just the type definition for screenProps would need to be modified for JSX3)
- uses records with optional fields instead of `@obj` creation functions for all options/config/param objects
- has less runtime (zero cost except for a little glue for the various `Navigator.Make` functions)
- is more complete (I went through the props/params for the various navigators in the React Navigation docs and added lots of missing stuff. I am sure that there is still more missing stuff remaining though.)
- is much simpler to use than the existing …

Full rewrite for JSX4, records with optional fields + simplicity

---

src/Native.res

Adding binding for prop - `independent` to be able to accommodate nested independent NavigationContainer

update: added independent param to NavigationContainer

---

src/BottomTabs.res
src/MaterialBottomTabs.res

by making the `tabBarLabel` argument to accept callback.
BottomTabs - https://github.com/react-navigation/react-navigation/blob/b62dccdf467e384362b6dc3399d4d5ac5537c7e1/packages/bottom-tabs/src/types.tsx#L121-L128
MaterialBottomTabs - https://github.com/react-navigation/react-navigation/blob/b62dccdf467e384362b6dc3399d4d5ac5537c7e1/packages/material-top-tabs/src/types.tsx#L96-L102
(This is a breaking change)

Improve binding of BottomTabs, MaterialBottomTabs
